extends: base.yaml

# Stage 1: Full training on Aligner only (freeze LLM+ViT)

tuner:
  train_type: full
  freeze_llm: true
  freeze_vit: true
  freeze_aligner: false

training:
  output_dir: ./output/stage_1_full_aligner_only
  run_name: stage_1_full_aligner_only
  add_version: true
  
  learning_rate: 1.0e-4
  vit_lr: 2.0e-5
  aligner_lr: 1.0e-4
  num_train_epochs: 4
  
  gradient_accumulation_steps: 8
  
  # Eval & checkpointing
  eval_strategy: steps
  eval_steps: 20
  save_strategy: steps
  save_steps: 1000
  save_total_limit: 2
  save_only_model: true
  
  # Verbose logging
  logging_dir: ./tb/stage_1_full_aligner_only
  logging_steps: 10
  logging_first_step: false

data:
  dataset_num_proc: 8
  dataloader_num_workers: 8
  eval_dataset: [placeholder]

deepspeed:
  enabled: true
  config: zero2

custom:
  train_jsonl: data/ds_v2_full/train.jsonl
  val_jsonl: data/ds_v2_full/val.jsonl
  augment_prob: 0.0
  dump_conversation_text: false