extends: base.yaml

# Stage 1: Full training on Aligner only (freeze LLM+ViT)

model:
  model: model_cache/models/Qwen/Qwen3-VL-4B-Instruct


prompts:
  scheme: B

tuner:
  train_type: full
  freeze_llm: true
  freeze_vit: true
  freeze_aligner: false

training:
  output_dir: ./output/stage_1_data_768
  run_name: eff_batch_32-lr_5e-4-epoch_10-data_768-per_image_2
  add_version: true
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  packing: true
  
  learning_rate: 5.0e-4
  vit_lr: 2.0e-5
  aligner_lr: 5.0e-4
  num_train_epochs: 10
  
  gradient_accumulation_steps: 2
  
  # Eval & checkpointing
  eval_strategy: steps
  eval_steps: 20
  save_strategy: best
  save_steps: 40
  save_total_limit: 2
  save_only_model: true
  
  # Verbose logging
  logging_dir: ./tb/10-22/stage_1_data_768
  logging_steps: 10
  logging_first_step: false

data:
  dataset_num_proc: 8
  dataloader_num_workers: 8
  eval_dataset: [placeholder]

deepspeed:
  enabled: true
  config: zero2

custom:
  augment_prob: 0.0
  images_per_user_turn: 2
  dump_conversation_text: false