extends: base.yaml

# Production Configuration - only differences from base

model:
  model: model_cache/models/Qwen/Qwen3-VL-4B-Instruct

template:
  max_pixels: 589824

tuner:
  train_type: lora
  lora_rank: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: [all-linear]
  freeze_llm: true
  freeze_vit: true
  freeze_aligner: false

prompts:
  scheme: B

training:
  output_dir: ./output/standard
  run_name: standard
  
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  packing: true
  
  learning_rate: 1.0e-4
  vit_lr: 2.0e-5
  aligner_lr: 1.0e-4
  num_train_epochs: 8
  
  gradient_accumulation_steps: 8
  
  eval_strategy: steps
  eval_steps: 100
  save_strategy: steps
  save_steps: 1000
  save_total_limit: 2
  save_only_model: true
  
  logging_dir: ./tb/standard
  logging_steps: 50
  logging_first_step: false

data:
  dataset_num_proc: 8
  dataloader_num_workers: 8
  eval_dataset: [placeholder]

deepspeed:
  enabled: true
  config: zero2

custom:
  train_jsonl: data/bbu_full_768/train.jsonl
  val_jsonl: data/bbu_full_768/val.jsonl
  augment_prob: 0.0
  images_per_user_turn: 2
  dump_conversation_text: false