extends: base.yaml

# Production Configuration - only differences from base

training:
  output_dir: ./output/standard
  run_name: standard
  
  learning_rate: 1.0e-4
  vit_lr: 2.0e-5
  aligner_lr: 1.0e-4
  num_train_epochs: 8
  
  gradient_accumulation_steps: 8
  
  eval_strategy: steps
  eval_steps: 100
  save_strategy: steps
  save_steps: 1000
  save_total_limit: 2
  save_only_model: true
  
  logging_dir: ./tb/standard
  logging_steps: 50
  logging_first_step: false

data:
  dataset_num_proc: 8
  dataloader_num_workers: 8
  eval_dataset: [placeholder]

deepspeed:
  enabled: true
  config: zero2

custom:
  train_jsonl: data/ds_v2_full/train.jsonl
  val_jsonl: data/ds_v2_full/val.jsonl
  augment_prob: 0.0
  dump_conversation_text: false